### ISSUE TITLE
Still SCP173 can't move. Blinking is disabled.

### ISSUE THREAD

**Issue by realmbmc** [Grover-c13/MultiAdmin#13]
I've downloaded latest servermod from here:
https://github.com/Grover-c13/MultiAdmin/releases/tag/SM1.1

But blinking still isn't fixed. Also I've found that SCP_DISABLE config parameters aren't working.
And also I've found that since 1.0 update there's a bug when sometimes player pickups the item from ground and it still appears to be at ground. BUT it is already taken and in players inventory. But it's copy still remains at ground and can be "fake" taken. The action is working but item doesn't move to inventory.

**Comment by Grover-c13** [comment]
Looks like im going to have to patch a fresh DLL, but im hesitant to do it right now since a new update is coming soon and its a lot of unfun work.

Ive confirmed the disable is working, see below for usage:
SCP049_DISABLE=yes;
SCP079_DISABLE=yes;
SCP106_DISABLE=yes;
SCP173_DISABLE=yes;

This will disable all SCPs.

**Comment by Grover-c13** [comment]
If anyone is reading this and doesnt want to ban 173, i suggest reverting to SM 0.6, the latest multiadmin will still work for the most part (the title bar wont display the player count, but its not a huge thing).

**Comment by Grover-c13** [comment]
No longer an issue as of https://github.com/Grover-c13/MultiAdmin/releases/tag/SM1.2
