### ISSUE TITLE
Cursor does not lock to game screen in new ServerMod

### ISSUE THREAD

**Issue by ADrySoldier** [Grover-c13/MultiAdmin#67]
Reproduced multiple times, whenever I use the 1.3 servermod I am unable to look around. Only way to fix it is to verify game files.

**Comment by Grover-c13** [comment]
You should copy your game folders and have a separate directory for your server, otherwise you wont get the new client updates and whatnot.

So in steamapps/common you should have
"SPC Secret Laboratory" - the original game files which you use to play
"SPC Secret Laboratory - server"  - copy of above but with servermod installed.

**Comment by Grover-c13** [comment]
Ive added a change to 1.4 that checks if the graphics device is null before removing the cursor lock, i stil lrecommend the above setup, but if you do use servermod client side the cursor will no longer lock.
